kmsConnector:
  enabled: false

kmsCore:
  enabled: false

kmsCoreClient:
  enabled: true
  image:
    name: ghcr.io/zama-ai/kms-core-client
    tag: v0.11.0-rc15
  envFrom:
    configmap:
      name: kms-threshold-1
  nodeSelector:
    karpenter.sh/nodepool: kms-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: kms-pool 

kmsInit:
  enabled: true
  nodeSelector:
    karpenter.sh/nodepool: kms-pool
  tolerations:
    - key: karpenter.sh/nodepool
      effect: NoSchedule
      operator: Equal
      value: kms-pool 



kmsGenKeys:
  enabled: false