# Configuration for the KMS peers
# This is used to define the number of peers and their IDs
kmsPeers:
  # Defines either the peer ID when count=1 or the start ID of a set of peers when count>1
  id: 1
  # The number of peers managed by the StatefulSets
  count: 1

kmsCore:
  # Add the following to enable the core:
  enabled: true
  # Override the name of the core:
  nameOverride:
  # Override the address of the core:
  addressOverride:
  # Override the image of the core:
  image:
    name: ghcr.io/zama-ai/kms-core
    tag: latest
    pullPolicy: Always
  # Define the service account name for the core:
  serviceAccountName:
  # Define the environment variables for the core:
  envFrom:
    configmap:
      name:
  # Add the following to enable threshold mode:
  thresholdMode:
    enabled: false
    # If left unset, the chart will generate the list automatically based on pod replicas of the statefulset
    peersList:
    #  - id: 1
    #    host: kms-core-1
    #    port: 50001
    #    ca_certificate:
    #      pem: |
    #        -----BEGIN CERTIFICATE-----
    #        -----END CERTIFICATE-----
    #  - id: 2
    #    host: kms-core-2
    #    port: 50001
    #    ca_certificate:
    #      pem: |
    #        -----BEGIN CERTIFICATE-----
    #        -----END CERTIFICATE-----

    # If enabled, the core will communicate with other cores over TLS
    tls:
      enabled: false
      attested: false
      # Core TLS certificates and keys can be loaded from file paths or from PEM
      # blocks NB: only PEM blocks are can be used to provide certificates to
      # Nitro enclaves!
      certificate:
        # You have to define either `path` or `pem`
        # Certificate: path to the certificate file
        path: /my/very/secret/cert.pem
        # Certificate: PEM block
        pem: |
          -----BEGIN CERTIFICATE-----
          -----END CERTIFICATE-----
      # Nitro enclaves will ignore this value since they generate their own
      # attested ephemeral keypairs
      privateKey:
        path: /my/very/secret/key.pem
      # If set, the enclave-enabled core will only establish TLS connections
      # with peers that have attested PCR0,1,2 values from this list
      trustedReleases:
        - pcr0: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
          pcr1: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
          pcr2: "000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000"
    # Threshold value is the number of corruptions that the protocol handles.
    # This value appears in the config file as `threshold`.
    thresholdValue: 1
    decCapacity: 10000
    minDecCache: 6000
    numSessionsPreproc: 2
    decryptionMode: "NoiseFloodSmall"
  # Add the following to enable nitro enclave:
  # Nitro enclave needs specific instance types
  nitroEnclave:
    enabled: false
    debug: true
    # Enclave CPU count, must be a multiple of 2 since whole cores (not hyperthreads) are sliced off and dedicated to the enclave
    cpuCount: 6
    # Enclave Memory in GiB
    memoryGiB: 20
    cid: 20
    eifPath: /app/kms/core/service/enclave.eif
    eifSignKey: 00000000-0000-0000-0000-000000000000
    userId: 10003
    groupId: 10002
    ports:
      tracing: 4317
      # For AWS authentication, set the `imds` or `sts` ports
      # To authenticate using either IMDS (with the Kubernetes node EC2 instance role) or STS (with the IRSA)
      imds: 5000
      sts: 5500
      s3: 6000
      awskms: 7000
      peer: 10000
      # Important, don't bind to port 9000 as it is reserved by Nitro for communicating with the enclave.
  publicVault:
    s3:
      enabled: true
      bucket: kms-public
      path: kms
  privateVault:
    s3:
      enabled: false
      bucket: kms-private
      path: kms
    awskms:
      enabled: false
      keychain: awskms://symm/00000000-0000-0000-0000-000000000000
  aws:
    roleArn:
    region: eu-west-1
  storage:
    # storageClassName: gp3
    capacity: 5Gi
  hostPort: true
  ports:
    client: 50100
    peer: 50001
    metrics: 9646
  workdir: /root
  serviceMonitor:
    enabled: false
  # Note: these requests/limits is only for non-enclave workloads, this will not be allocated to the kms-core process running in Nitro
  resources:
    requests: {}
      # memory: 1Gi
      # cpu: 1
    limits:
      # memory: 30Gi
      ephemeralStorage: 1Gi
      grpcTimeout: 360
      # 100MB
      grpcMaxMessageSize: 104857600
  nodeSelector:
  affinity:
  tolerations:
mtls:
  enabled: false

kmsCoreClient:
  enabled: false
  nameOverride:
  image:
    name: ghcr.io/zama-ai/kms-core-client
    tag: latest
  envFrom:
    configmap:
      name:
  num_majority: 2
  num_reconstruct: 3
  decryption_mode: "NoiseFloodSmall"
  fhe_parameter: Test
  storage:
    # storageClassName: gp3
    capacity: 1Gi
  resources:
    requests: {}
      # memory: 1Gi
      # cpu: 1
    limits: {}
      # memory: 30Gi
      # cpu: 1
  nodeSelector:
  affinity:
  tolerations:

# Threshold Init job
kmsInit:
  enabled: false
  nameOverride:
  nodeSelector:
  affinity:
  tolerations:

# Automatic Key Generation job
kmsGenKeys:
  enabled: false
  nameOverride:
  # command line arguments passed to kms-core-client
  keyGenArgs: "insecure-key-gen"
  crsGenArgs: "insecure-crs-gen --max-num-bits 1024"
  configmap:
    name: kms-keys
    annotations:

kubeUtils:
  image:
    name: ghcr.io/zama-ai/kube-utils
    tag: 0.2.0
    pullPolicy: Always

runMode: dev

redis:
  enabled: false
  host: "redis://redis-master.common.svc.cluster.local"

tracing:
  enabled: false
  endpoint: "http://otel-deployment-opentelemetry-collector.observability.svc.cluster.local:4317"
  otlp_timeout_ms: 10000

minio:
  enabled: false
  fullnameOverride: minio
  auth:
    rootUser: minio-admin
    rootPassword: minio-admin
  provisioning:
    enabled: true
    buckets:
      - name: kms-public
        region: eu-west-1
    users:
      - username: kms-access-key-id
        password: kms-secret-access-key
        policies:
          - readwrite
    extraCommands:
      - "mc anonymous set public provisioning/kms-public"

rustLog: info

# Add pod annotations to the kms-core
# podAnnotations:
#   configmap.reloader.stakater.com/auto: "true"

podSecurityContext:
  # To set when the image will support non root user
  #  runAsUser: 1000
  #  runAsGroup: 1000
  #  fsGroup: 1000
  #  runAsNonRoot: true
  allowPrivilegeEscalation: false
  readOnlyRootFilesystem: true
  capabilities:
    drop:
      - ALL
  privileged: false

podSecurityContextForEnclave:
  fsGroup: 1001     # Keep this as 1001 to match device group
  supplementalGroups: [1001]  # Add device group as supplemental

kyverno:
  enabled: false

# Cronjob kubernetes
kmsCoreClientTesting:
  enabled: false
  nameOverride: ""
  schedule: "*/5 * * * *"
  resources:
    requests: {}
      # memory: 1Gi
      # cpu: 1
    limits: {}
      # memory: 30Gi
      # cpu: 1
  shell_command:
  storage:
    storageClassName: gp3
    capacity: 5Gi
