{{- if .Values.kmsCoreClient.enabled -}}
{{- $peersIDList := untilStep (include "kmsPeersStartID" . | int) (.Values.kmsPeers.count | add1 | int) 1  }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kms-core-client
  name: {{ include "kmsCoreClientName" . }}-config
data:
  load-core-client-config.sh: |
    #!/usr/bin/env sh
    set -e
    echo "loading configuration from env vars into the config.toml file"

    # Process the S3 endpoint if it contains a variable
    if echo "$S3_ENDPOINT" | grep -q '\$'; then
        S3_ENDPOINT=$(eval echo "$S3_ENDPOINT")
    fi

    if [ -n "${CORE_CLIENT__S3_ENDPOINT}" ]; then
      S3_ENDPOINT="${CORE_CLIENT__S3_ENDPOINT}"
    fi

    cat <<EOF >>config.toml
    s3_endpoint="${S3_ENDPOINT}"
    object_folder=${OBJECT_FOLDER}
    core_addresses=${CORE_ADDRESSES}
    num_majority=${NUM_MAJORITY}
    num_reconstruct=${NUM_RECONSTRUCT}
    decryption_mode=${DECRYPTION_MODE}
    fhe_params=${FHE_PARAMETER:=Test}
    EOF

    # Keep the pod running
    tail -f /dev/null

  load-core-client-testing-config.sh: |
    #!/usr/bin/env sh
    set -e

    echo "loading configuration from env vars into the config.toml file"

    # Process the S3 endpoint if it contains a variable
    if echo "$S3_ENDPOINT" | grep -q '\$'; then
        S3_ENDPOINT=$(eval echo "$S3_ENDPOINT")
    fi

    if [ -n "${CORE_CLIENT__S3_ENDPOINT}" ]; then
      S3_ENDPOINT="${CORE_CLIENT__S3_ENDPOINT}"
    fi

    cat <<EOF >>config.toml
    s3_endpoint="${S3_ENDPOINT}"
    object_folder=${OBJECT_FOLDER}
    core_addresses=${CORE_ADDRESSES}
    num_majority=${NUM_MAJORITY}
    num_reconstruct=${NUM_RECONSTRUCT}
    decryption_mode=${DECRYPTION_MODE}
    fhe_params=${FHE_PARAMETER:=Test}
    EOF

    {{- range .Values.kmsCoreClientTesting.shell_command }}
    {{ . }}
    {{- end }}

{{- end -}}
