{{- if .Values.kmsCore.enabled -}}
{{- $kmsCoreName := include "kmsCoreName" . }}
{{- $peersIDList := untilStep (include "kmsPeersStartID" . | int) (.Values.kmsPeers.count | add1 | int) 1  }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: kms-core
    app.kubernetes.io/name: {{ include "kmsCoreName" . }}
  name: {{ include "kmsCoreName" . }}-config
data:
  kms-server.toml: |
    [service]
    listen_address = "0.0.0.0"
    listen_port = {{ int .Values.kmsCore.ports.client }}
    timeout_secs = {{ int .Values.kmsCore.resources.limits.grpcTimeout }}
    grpc_max_message_size = {{ int .Values.kmsCore.resources.limits.grpcMaxMessageSize }}

    [aws]
    region = "${AWS_REGION}"
    role_arn = "${AWS_ROLE_ARN}"
    {{- if .Values.minio.enabled }}
    s3_endpoint = "http://minio:9000"
    {{- else }}
    {{- if .Values.kmsCore.nitroEnclave.enabled }}
    {{- if .Values.kmsCore.nitroEnclave.ports.imds }}
    imds_endpoint = "http://localhost:{{ .Values.kmsCore.nitroEnclave.ports.imds }}"
    {{- end }}
    {{- if .Values.kmsCore.nitroEnclave.ports.sts }}
    sts_endpoint = "https://localhost:{{ .Values.kmsCore.nitroEnclave.ports.sts }}"
    {{- end }}
    s3_endpoint = "https://localhost:{{ .Values.kmsCore.nitroEnclave.ports.s3 }}"
    awskms_endpoint = "https://localhost:{{ .Values.kmsCore.nitroEnclave.ports.awskms }}"
    {{- end }}
    {{- end }}

    [public_vault]
    storage = "${KMS_CORE__PUBLIC_VAULT__STORAGE}"

    [private_vault]
    storage = "${KMS_CORE__PRIVATE_VAULT__STORAGE}"
    {{- if .Values.kmsCore.nitroEnclave.enabled }}
    keychain = "${KMS_CORE__PRIVATE_VAULT__KEYCHAIN}"
    {{- end }}

    {{ if .Values.kmsCore.thresholdMode.enabled -}}
    [threshold]
    listen_address = "0.0.0.0"
    listen_port = {{ int .Values.kmsCore.ports.peer }}

    my_id = "${KMS_CORE__THRESHOLD__MY_ID}"

    # Threshold is the number of corruptions that the protocol handles.
    threshold = {{ int .Values.kmsCore.thresholdMode.thresholdValue }}
    dec_capacity = {{ int .Values.kmsCore.thresholdMode.decCapacity }}
    min_dec_cache = {{ int .Values.kmsCore.thresholdMode.minDecCache }}
    num_sessions_preproc = {{ int .Values.kmsCore.thresholdMode.numSessionsPreproc }}
    decryption_mode = {{ .Values.kmsCore.thresholdMode.decryptionMode | quote }}

    {{ if $.Values.kmsCore.thresholdMode.tls.enabled }}
    [threshold.tls]
    {{- if .Values.kmsCore.thresholdMode.tls.certificate.path }}
    cert.path = {{ .Values.kmsCore.thresholdMode.tls.certificate.path | quote }}
    {{- else }}
    cert.pem = {{ .Values.kmsCore.thresholdMode.tls.certificate.pem | toToml }}
    {{- end }}
    {{- if $.Values.kmsCore.nitroEnclave.enabled }}
    {{- if .Values.kmsCore.thresholdMode.tls.trustedReleases }}
    {{ range .Values.kmsCore.thresholdMode.tls.trustedReleases }}
    [[threshold.tls.key.enclave.trustedReleases]]
    pcr0 = {{ .pcr0 | quote }}
    pcr1 = {{ .pcr1 | quote }}
    pcr2 = {{ .pcr2 | quote }}
    {{- end }}
    {{- end }}
    {{- else }}
    {{- if .Values.kmsCore.thresholdMode.tls.privateKey.path }}
    key.path = {{ .Values.kmsCore.thresholdMode.tls.privateKey.path | quote }}
    {{- else }}
    key.pem = {{ .Values.kmsCore.thresholdMode.tls.privateKey.path | toToml }}
    {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.kmsCore.thresholdMode.peersList }}
    {{ range .Values.kmsCore.thresholdMode.peersList }}
    [[threshold.peers]]
    party_id = {{ int .id }}
    {{- if $.Values.kmsCore.nitroEnclave.enabled }}
    address = "localhost"
    port = {{ add $.Values.kmsCore.nitroEnclave.ports.peer .id }}
    {{- else }}
    address = {{ .host | quote }}
    port = {{ int .port }}
    {{- end }}
    {{- if $.Values.kmsCore.thresholdMode.tls.enabled }}
    {{- if .ca_certificate.path }}
    tls_cert.path = {{ .ca_certificate.path | quote }}
    {{- else }}
    tls_cert.pem = {{ .ca_certificate.pem | toToml }}
    {{- end }}
    {{- end }}
    {{- end }}
    {{- end }}

    {{- if not .Values.kmsCore.thresholdMode.peersList }}
    {{ range $i := $peersIDList }}
    [[threshold.peers]]
    party_id = {{ int $i }}
    {{- if $.Values.kmsCore.nitroEnclave.enabled }}
    address = "localhost"
    port = {{ add $.Values.kmsCore.nitroEnclave.ports.peer $i }}
    {{ else }}
    address = {{ (printf "%s-%d" $kmsCoreName $i) | quote }}
    port = {{ int $.Values.kmsCore.ports.peer }}
    {{- end }}
    {{- end }}
    {{- end }}

    {{- if .Values.redis.enabled -}}
    [threshold.preproc_redis]
    host = {{ .Values.redis.host | quote }}
    {{- end }}
    {{- end }}

    {{- if .Values.tracing.enabled }}
    [telemetry]
    tracing_service_name = {{ include "kmsCoreName" . | quote }}
    {{- if .Values.kmsCore.nitroEnclave.enabled }}
    tracing_endpoint = "http://localhost:{{ .Values.kmsCore.nitroEnclave.ports.tracing }}"
    {{- else }}
    tracing_endpoint = {{ .Values.tracing.endpoint | quote }}
    {{- end }}
    tracing_otlp_timeout_ms = 10000
    metrics_bind_address = "0.0.0.0:{{ .Values.kmsCore.ports.metrics }}"

    [telemetry.batch]
    max_queue_size = 8192
    max_export_batch_size = 2048
    max_concurrent_exports = 4
    scheduled_delay_ms = 500
    export_timeout_ms = 5000

    [threshold.core_to_core_net]
    message_limit = 70
    multiplier = 1.1
    max_interval = 5
    max_elapsed_time = 300
    network_timeout = 10
    network_timeout_bk = 300
    network_timeout_bk_sns = 1200
    max_en_decode_message_size = 2147483648

    [rate_limiter_conf]
    bucket_size = 50000
    pub_decrypt = 1
    user_decrypt = 1
    crsgen = 100
    preproc = 50000
    keygen = 1000
    {{- end }}

    {{- if .Values.kmsCore.nitroEnclave.enabled }}
  enclave.json: |
    {
      "cpu_count": {{ int .Values.kmsCore.nitroEnclave.cpuCount }},
      "memory_mib": {{ mulf 1024 (int .Values.kmsCore.nitroEnclave.memoryGiB) }},
      "enclave_cid": {{ int .Values.kmsCore.nitroEnclave.cid }},
      "eif_path": {{ .Values.kmsCore.nitroEnclave.eifPath | quote }}
    }
    {{- if .Values.kmsCore.thresholdMode.tls.enabled }}
  party_cert.pem: {{ .Values.kmsCore.thresholdMode.tls.certificate.pem | toYaml | indent 2 }}
    {{- end }}
    {{- end }}
{{- end -}}
