{{- if .Values.kmsCore.enabled -}}
{{- $kmsCoreName := include "kmsCoreName" . -}}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kms-core
    app.kubernetes.io/name: {{ $kmsCoreName }}
    headless: "true"
  name: {{ $kmsCoreName }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - name: client
      port: {{ .Values.kmsCore.ports.client }}
      targetPort: {{ .Values.kmsCore.ports.client }}
    {{- if .Values.kmsCore.thresholdMode.enabled }}
    - name: peer
      port: {{ .Values.kmsCore.ports.peer }}
      targetPort: {{ .Values.kmsCore.ports.peer }}
    {{- end }}
  selector:
    app: kms-core
    app.kubernetes.io/name: {{ $kmsCoreName }}
{{- $numberReplicas := .Values.kmsCore.replicas | default .Values.kmsPeers.count }}
{{- range $coreId := untilStep (.Values.kmsPeers.id | int) ($numberReplicas | add .Values.kmsPeers.id | int) 1 }}
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: kms-core
    app.kubernetes.io/name: {{ $kmsCoreName }}
    headless: "false"
  name: {{ $kmsCoreName }}-{{ $coreId }}
spec:
  type: ClusterIP
  ports:
    - name: client
      port: {{ $.Values.kmsCore.ports.client }}
      targetPort: {{ $.Values.kmsCore.ports.client }}
    {{- if $.Values.kmsCore.thresholdMode.enabled }}
    - name: peer
      port: {{ $.Values.kmsCore.ports.peer }}
      targetPort: {{ $.Values.kmsCore.ports.peer }}
    {{- end }}
    - name: metrics
      port: {{ $.Values.kmsCore.ports.metrics }}
      targetPort: {{ $.Values.kmsCore.ports.metrics }}
  selector:
    app: kms-core
    app.kubernetes.io/name: {{ $kmsCoreName }}
    statefulset.kubernetes.io/pod-name: {{ $kmsCoreName }}-{{ $coreId }}
{{- end }}
{{- end -}}
