{{- if and .Values.kmsCore.enabled .Values.kmsCore.serviceMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    app: kms-core
    app.kubernetes.io/name: {{ include "kmsCoreName" . }}
  name: {{ include "kmsCoreName" . }}
spec:
  selector:
    matchLabels:
      app: kms-core
      app.kubernetes.io/name: {{ include "kmsCoreName" . }}
      headless: "false"
  endpoints:
  - port: metrics
    relabelings:
    - action: replace
      regex: .*:(.*)
      replacement: $1
      sourceLabels:
      - __meta_kubernetes_pod_container_image
      targetLabel: image_tag
{{- end -}}
